spring.application.name=order-management

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.default-requeue-rejected=false

spring.data.mongodb.uri=mongodb://localhost:27017/order_manegement

spring.redis.host=${HOST:localhost}
spring.redis.port=${PORT:6379}
spring.redis.password=${PASSWORD:password}
spring.cache.type=redis
spring.cache.cache-names=orders_manegemnt_methods

